on:
  issues:
    types: [opened]

jobs:

  run-term-usage-report:
    if: contains(github.event.issue.labels.*.name, 'term_usage')
    runs-on: ubuntu-22.04
    name: Run term usage report
    steps:
      - name: Proof of env
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: |
          echo A comment on issue $NUMBER
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python virtual environment
        run: python3 -m venv .venv && . .venv/bin/activate && pip install oaklib requests pytz
      - name: Run term usage script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: . .venv/bin/activate && mkdir -p reports/$NUMBER && python3 ./scripts/term-usage-report.py geneontology/annotation-query 7 --number $NUMBER --label term_usage --output ./reports/$NUMBER --verbose
      - name: Commit and push reports
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: |
          git config user.email sjcarbon@lbl.gov
          git config user.name sjcarbon
          git add reports/
          git diff --cached --quiet && exit 0
          git commit -m "Reports at https://github.com/geneontology/annotation-query/tree/main/reports/${NUMBER} for issue https://github.com/geneontology/annotation-query/issues/${NUMBER}"
          for i in 1 2 3 4 5; do
            git pull --rebase origin main && git push && exit 0
            sleep $((RANDOM % 5 + 3))
          done
          exit 1
