on:
  issues:
    types: [opened]

jobs:

  run-term-usage-report:
    if: contains(github.event.issue.labels.*.name, 'term_usage')
    runs-on: ubuntu-22.04
    name: Run term usage report
    steps:
      - name: Proof of env
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: |
          echo A comment on issue $NUMBER
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python virtual environment
        run: python3 -m venv .venv && . .venv/bin/activate && pip install oaklib requests pytz
      - name: Run term usage script
        env:
          NUMBER: ${{ github.event.issue.number }}
        run: . .venv/bin/activate && mkdir -p reports/$NUMBER && python3 ./scripts/term-usage-report.py geneontology/annotation-query 7 --number $NUMBER --label term_usage --output ./reports/$NUMBER --verbose
      - name: Commit reports back to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            Reports at https://github.com/geneontology/annotation-query/tree/main/reports/${{ github.event.issue.number }} for issue https://github.com/geneontology/annotation-query/issues/${{ github.event.issue.number }}
          commit_user_email: sjcarbon@lbl.gov
          # Please do the dirty check, don't skip
          skip_dirty_check: false
